import type { GameProgress, KnowledgeSource, Quest, WikiCard } from './types'

const now = '2026-05-24T00:00:00.000Z'
const reviewDue = '2026-05-31T00:00:00.000Z'

export const phaseOneSource: KnowledgeSource = {
  id: '11111111-1111-4111-8111-111111111111',
  title: '图文课程：建立知识体系，一年顶别人十年',
  sourceType: 'pdf-methodology',
  sourceUri: 'C:/Users/宇宙无敌小仙女本仙/Desktop/图文课程：建立知识体系，一年顶别人十年.pdf',
  rawExcerpt: null,
  summary: 'Phase 1 只沉淀方法论骨架：角色、学习飞轮、知识漏洞、计划、输入、沉淀、复盘、应用。',
  theme: '00_通用知识体系',
  status: 'Structured',
  metadata: {
    copyright_boundary: 'No full-text reproduction. Summary and method cards only.',
    pipeline: 'PDF -> DIKIW card -> knowledge-game',
  },
  createdAt: now,
  updatedAt: now,
}

export const seedCards: WikiCard[] = [
  {
    id: '22222222-2222-4222-8222-222222222201',
    sourceId: phaseOneSource.id,
    slug: 'role-based-learning-purpose',
    title: '学习要为角色服务',
    summary: '学习不是囤资料，而是为了扮演好当前角色和想成为的角色；所有输入都要能回到角色问题。',
    theme: '00_通用知识体系',
    status: 'Understood',
    dikiwLevel: 'Knowledge',
    bloomType: '元认知知识',
    role: '终身学习者',
    tags: ['角色', '学习目标', '知识体系'],
    keyTakeaways: ['先梳理自己正在扮演的角色', '每个角色都对应一组要解决的问题', '知识是否入库取决于它能否服务角色'],
    actionSuggestion: '为每个重要角色写下愿景、目标、原则和当前最卡的三个问题。',
    feishuUrl: null,
    reviewDueAt: reviewDue,
    masteryScore: 58,
    metadata: { phase: 1, source: 'methodology-summary' },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: '22222222-2222-4222-8222-222222222202',
    sourceId: phaseOneSource.id,
    slug: 'learning-flywheel',
    title: '学习飞轮：输入、理解、沉淀、输出',
    summary: '有效学习需要完成输入、理解、沉淀、输出四个环节，缺一环就容易变成低效收藏。',
    theme: '00_通用知识体系',
    status: 'Understood',
    dikiwLevel: 'Knowledge',
    bloomType: '概念性知识',
    role: '终身学习者',
    tags: ['学习飞轮', '输入', '输出'],
    keyTakeaways: ['输入负责捕捉材料', '理解负责加工意义', '沉淀负责形成长期资产', '输出负责应用和反馈'],
    actionSuggestion: '每张知识卡都标注它目前卡在哪一环，并用任务推进到下一环。',
    feishuUrl: null,
    reviewDueAt: reviewDue,
    masteryScore: 62,
    metadata: { phase: 1, source: 'methodology-summary' },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: '22222222-2222-4222-8222-222222222203',
    sourceId: phaseOneSource.id,
    slug: 'knowledge-system-split',
    title: '知识体系分为通用层和专用层',
    summary: '通用知识服务多个角色，专用知识服务特定角色；两者分开，知识才不会越堆越乱。',
    theme: '00_通用知识体系',
    status: 'Structured',
    dikiwLevel: 'Knowledge',
    bloomType: '概念性知识',
    role: '知识管理者',
    tags: ['通用知识', '专用知识', '分类'],
    keyTakeaways: ['通用层包含底层素质、通用能力、通用技能、通用知识', '专用层包含角色态度、专业技能、专业知识'],
    actionSuggestion: '新输入先判断是否能服务两个以上角色，能则进通用层，否则进入对应专用主题。',
    feishuUrl: null,
    reviewDueAt: reviewDue,
    masteryScore: 45,
    metadata: { phase: 1, source: 'methodology-summary' },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: '22222222-2222-4222-8222-222222222204',
    sourceId: phaseOneSource.id,
    slug: 'knowledge-gap-learning-plan',
    title: '从知识漏洞生成学习计划',
    summary: '学习重点来自角色问题：先列问题，再拆所需知识，最后找自己缺的程序性知识和概念性知识。',
    theme: '00_通用知识体系',
    status: 'Structured',
    dikiwLevel: 'Insight',
    bloomType: '程序性知识',
    role: '终身学习者',
    tags: ['知识漏洞', '学习计划', 'Bloom'],
    keyTakeaways: ['不要问我要学什么，先问角色要解决什么问题', '程序性知识回答怎么做', '概念性知识回答为什么和如何判断'],
    actionSuggestion: '每周围绕一个角色问题制定学习计划，并把计划绑定到具体输出。',
    feishuUrl: null,
    reviewDueAt: reviewDue,
    masteryScore: 50,
    metadata: { phase: 1, source: 'methodology-summary' },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: '22222222-2222-4222-8222-222222222205',
    sourceId: phaseOneSource.id,
    slug: 'review-and-deliberate-practice',
    title: '复盘让知识从卡片变成肌肉记忆',
    summary: '复习不是重读笔记，而是通过自我测试、知识输出、模拟实战和整理体系，推动知识可用、可迁移。',
    theme: '00_通用知识体系',
    status: 'Reviewed',
    dikiwLevel: 'Wisdom',
    bloomType: '元认知知识',
    role: '知识管理者',
    tags: ['复盘', '刻意练习', '迁移'],
    keyTakeaways: ['碎片时间做自我测试', '专用时间做周/月复盘', '实战后记录应用体会', '把专用经验抽象回通用层'],
    actionSuggestion: '每天清空输入队列，每周复盘一个主题，每月整理一次体系升降级。',
    feishuUrl: null,
    reviewDueAt: reviewDue,
    masteryScore: 72,
    metadata: { phase: 1, source: 'methodology-summary' },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: '22222222-2222-4222-8222-222222222206',
    sourceId: phaseOneSource.id,
    slug: 'avoid-knowledge-capture',
    title: '不要被知识绑架',
    summary: '知识只是素材，真正重要的是在具体问题里判断该不该用、怎么用、何时不用。',
    theme: '00_通用知识体系',
    status: 'Mastered',
    dikiwLevel: 'Wisdom',
    bloomType: '元认知知识',
    role: '决策者',
    tags: ['具体问题具体分析', '思考系统', 'Boss战'],
    keyTakeaways: ['不要拿单一理论解释所有问题', '学习系统提供素材，思考系统负责判断', '最终目标是驾驭知识而不是崇拜知识'],
    actionSuggestion: '进入 Boss 战时必须说明某张知识卡的适用边界和不用它的条件。',
    feishuUrl: null,
    reviewDueAt: reviewDue,
    masteryScore: 88,
    metadata: { phase: 1, source: 'methodology-summary', boss: '知识绑架者' },
    createdAt: now,
    updatedAt: now,
  },
]

export const seedQuests: Quest[] = [
  {
    id: 'intake-lighthouse',
    questType: 'intake',
    title: '输入关：点亮入口灯塔',
    description: '收集一条新知识，判断它是否值得上库，并完成主题分流。',
    theme: '00_通用知识体系',
    requiredStatus: 'Captured',
    rewardXp: 15,
    sortOrder: 10,
    active: true,
    metadata: { phase: 2 },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'understand-seven-lens',
    questType: 'understand',
    title: '理解关：七多透镜',
    description: '用例子、类比、多来源、多角度和追问为什么，把知识从看过推进到理解。',
    theme: '00_通用知识体系',
    requiredStatus: 'Structured',
    rewardXp: 20,
    sortOrder: 20,
    active: true,
    metadata: { phase: 3 },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'craft-wiki-card',
    questType: 'craft',
    title: '铸卡关：锻造 Wiki 卡',
    description: '把一条材料沉淀成可复用、可检索、可复盘的 DIKIW 知识卡。',
    theme: '00_通用知识体系',
    requiredStatus: 'Structured',
    rewardXp: 25,
    sortOrder: 30,
    active: true,
    metadata: { phase: 3 },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'output-feynman',
    questType: 'output',
    title: '输出关：费曼篝火',
    description: '用自己的话讲明白一张卡，让知识从沉淀走向输出。',
    theme: '00_通用知识体系',
    requiredStatus: 'Understood',
    rewardXp: 30,
    sortOrder: 40,
    active: true,
    metadata: { phase: 3 },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'practice-field',
    questType: 'practice',
    title: '实战关：具体问题训练场',
    description: '选择一个真实问题，说明这张知识卡如何帮助行动，并记录应用体会。',
    theme: '00_通用知识体系',
    requiredStatus: 'Applied',
    rewardXp: 40,
    sortOrder: 50,
    active: true,
    metadata: { phase: 3 },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'boss-knowledge-capture',
    questType: 'boss',
    title: 'Boss 战：知识绑架者',
    description: '证明你能判断知识的适用边界：什么时候该用、怎么用、什么时候不该用。',
    theme: '00_通用知识体系',
    requiredStatus: 'Reviewed',
    rewardXp: 80,
    sortOrder: 60,
    active: true,
    metadata: { phase: 3, boss: true },
    createdAt: now,
    updatedAt: now,
  },
]

export const seedProgress: GameProgress = {
  id: '33333333-3333-4333-8333-333333333333',
  profileKey: 'solo',
  xp: 185,
  level: 3,
  currentPhase: 1,
  reviewedCards: 1,
  masteredCards: 1,
  lastReviewAt: null,
  metadata: {
    title: '知识星图冒险者',
    boss: '知识绑架者',
  },
  updatedAt: now,
}
